# 预发环境配置
server:
  port: 8080

spring:
  # 数据源配置 - 预发环境数据库
  datasource:
    url: jdbc:mysql://staging-db.miniservehub.com:3306/miniservehub_staging?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:miniservehub_staging}
    password: ${DB_PASSWORD}
    druid:
      initial-size: 15
      min-idle: 15
      max-active: 80
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD}
        reset-enable: false
        allow: ${DRUID_ALLOW_IPS:127.0.0.1,10.0.0.0/8}
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  # Redis配置 - 预发环境Redis集群
  data:
    redis:
      host: ${REDIS_HOST:staging-redis.miniservehub.com}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 32
          max-wait: -1ms
          max-idle: 16
          min-idle: 4

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

# 日志配置
logging:
  level:
    com.miniservehub: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.cache: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: logs/miniservehub-staging.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 15

# Druid监控配置已合并到上面的spring配置中

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: never
  server:
    port: 9090

# 业务配置
miniservehub:
  env: staging
  debug: false
  cache:
    default-ttl: 3600
  security:
    enable-cors: false
